ENG-5164 WIP: Debugging crane issue

diff --git a/.github/workflows/entando-release.yml b/.github/workflows/entando-release.yml
--- a/.github/workflows/entando-release.yml
+++ b/.github/workflows/entando-release.yml
@@ -109,34 +109,45 @@ jobs:
           CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
         run: |
           for IMAGE in $(echo "$CLIENT_PAYLOAD" | jq -c '.images[]'); do
-            for DOCKER_HUB_REPO in $(echo "$DOCKER_HUB_REPOS" | jq -c '.images[]'); do
-              IMAGE_NAME=$(echo $IMAGE | jq -r '.name')
-              REPO_NAMESPACE=$(echo $DOCKER_HUB_REPO | jq -r '.docker_hub_namespace')
-              REPO=$(echo $DOCKER_HUB_REPO | jq -r '.docker_hub_repository')
-              NEW_VERSION=$(echo $IMAGE | jq -r '.version')
-              echo $IMAGE_NAME
-              echo $REPO_NAMESPACE
-              echo $REPO
-              echo $NEW_VERSION
-              echo ${REPO_NAMESPACE}/${REPO}:${NEW_VERSION}
-              NEW_DIGEST="$(crane digest ${REPO_NAMESPACE}/${REPO}:${NEW_VERSION})"
-              #if [[ $NEW_DIGEST = false ]]
-              #then
-              #  echo "::error :: Version '$NEW_VERSION' does not exist for '$IMAGE_NAME'"
-              #  exit 5
-              #fi
-              echo "This is the digest: ${NEW_DIGEST}"
-              ORIGINAL_VERSION=$(yq ".operator.relatedImages.$IMAGE_NAME.version" values.yaml)
-              ORIGINAL_SHA=$(yq ".operator.relatedImages.$IMAGE_NAME.sha256" values.yaml)
-              yq -i ".operator.relatedImages.$IMAGE_NAME.version = $NEW_VERSION" values.yaml
-              yq -i ".operator.relatedImages.$IMAGE_NAME.sha256 = $NEW_DIGEST" values.yaml
-              # Print the original and updated version and SHA digest of the Docker image
-              echo "Updating values.yaml"
-              echo "Image name: $IMAGE_NAME"
-              echo 'Original data: version="'$ORIGINAL_VERSION'", sha="'$ORIGINAL_SHA'"'
-              echo 'New data: version="'$NEW_VERSION'", sha='$NEW_DIGEST
-              echo ""
-            done
+            FOUND_IMAGE=false
+            if [[ $IMAGE_NAME == $REPO_NAME ]]
+            then
+              FOUND_IMAGE=true
+              for DOCKER_HUB_REPO in $(echo "$DOCKER_HUB_REPOS" | jq -c '.images[]'); do
+                IMAGE_NAME=$(echo $IMAGE | jq -r '.name')
+                REPO_NAMESPACE=$(echo $DOCKER_HUB_REPO | jq -r '.docker_hub_namespace')
+                REPO=$(echo $DOCKER_HUB_REPO | jq -r '.docker_hub_repository')
+                NEW_VERSION=$(echo $IMAGE | jq -r '.version')
+                echo $IMAGE_NAME
+                echo $REPO_NAMESPACE
+                echo $REPO
+                echo $NEW_VERSION
+                echo ${REPO_NAMESPACE}/${REPO}:${NEW_VERSION}
+                NEW_DIGEST="$(crane digest ${REPO_NAMESPACE}/${REPO}:${NEW_VERSION})"
+                #if [[ $NEW_DIGEST = false ]]
+                #then
+                #  echo "::error :: Version '$NEW_VERSION' does not exist for '$IMAGE_NAME'"
+                #  exit 5
+                #fi
+                echo "This is the digest: ${NEW_DIGEST}"
+                ORIGINAL_VERSION=$(yq ".operator.relatedImages.$IMAGE_NAME.version" values.yaml)
+                ORIGINAL_SHA=$(yq ".operator.relatedImages.$IMAGE_NAME.sha256" values.yaml)
+                yq -i ".operator.relatedImages.$IMAGE_NAME.version = $NEW_VERSION" values.yaml
+                yq -i ".operator.relatedImages.$IMAGE_NAME.sha256 = $NEW_DIGEST" values.yaml
+                # Print the original and updated version and SHA digest of the Docker image
+                echo "Updating values.yaml"
+                echo "Image name: $IMAGE_NAME"
+                echo 'Original data: version="'$ORIGINAL_VERSION'", sha="'$ORIGINAL_SHA'"'
+                echo 'New data: version="'$NEW_VERSION'", sha='$NEW_DIGEST
+                echo ""
+              done
+              fi
+            # If the Docker image doesn't exist in the Docker Hub repositories configuration, exit with an error
+            if [[ $FOUND_IMAGE = false ]]
+            then
+              echo "::error :: Image '$IMAGE_NAME' does not exist in '$DOCKER_HUB_REPOS_CONFIG_URL'"
+              exit 6
+            fi
           done
 
       # Generating kustomization files for K8S and OCP environments
