IT-319 Removing the duplicated creation of entando-releases tag and adding some logs

diff --git a/.github/workflows/entando-release.yml b/.github/workflows/entando-release.yml
--- a/.github/workflows/entando-release.yml
+++ b/.github/workflows/entando-release.yml
@@ -191,6 +191,7 @@ jobs:
           MAKE_LATEST=legacy
         fi
         PAYLOAD='{"tag_name":"${{ env.RELEASE_TAG }}","target_commitish":"${{ env.RELEASE_BRANCH }}","name":"${{ env.RELEASE_TAG }}","body":"${{ env.RELEASE_TAG }} release","draft":false,"prerelease":false,"generate_release_notes":true,"make_latest":"'$MAKE_LATEST\"}
+        echo $PAYLOAD
         curl \
           -X POST \
           -H "Accept: application/vnd.github+json" \
@@ -211,7 +212,18 @@ jobs:
       with:
         repository: ${{ env.ENTANDO_RELEASES_REPO }}
         ref: ${{ env.RELEASE_BRANCH }}
-        token: ${{ secrets.ENTANDO_BOT_TOKEN }}       
+        token: ${{ secrets.ENTANDO_BOT_TOKEN }}
+        fetch-depth: 0        
+
+    # Validate the release tag
+    - name: Validate release tag
+      run: |
+        # Check if the release tag already exists
+        if [[ $(git tag -l $RELEASE_TAG) ]]
+        then
+            echo "::error :: Tag '$RELEASE_TAG' already exists"
+            exit 7
+        fi
         
     # Update the manifest file
     - name: Update manifest file
@@ -243,7 +255,7 @@ jobs:
           fi
           if [[ $CATALOG_SHA_UPDATED = true ]]
           then
-            echo "OKD_CATALOG_IMAGE value uploaded to '${INDEX_SHA}'. Exiting "
+            echo "OKD_CATALOG_IMAGE value updated to '${INDEX_SHA}'. Exiting"
             rm result.json
             break
           else
@@ -278,9 +290,8 @@ jobs:
         then
           MAKE_LATEST=legacy
         fi
-        git tag ${{ env.RELEASE_TAG }} ${{ env.RELEASE_BRANCH }}
-        git push origin ${{ env.RELEASE_TAG }}
         PAYLOAD='{"tag_name":"${{ env.RELEASE_TAG }}","target_commitish":"${{ env.RELEASE_BRANCH }}","name":"${{ env.RELEASE_TAG }}","body":"${{ env.RELEASE_TAG }} release","draft":false,"prerelease":false,"generate_release_notes":true,"make_latest":"'$MAKE_LATEST\"}
+        echo $PAYLOAD
         curl \
           -X POST \
           -H "Accept: application/vnd.github+json" \
@@ -329,7 +340,7 @@ jobs:
             -H "Authorization: Bearer ${{ secrets.ENTANDO_BOT_TOKEN }}"\
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/${{ env.ENTANDO_RELEASES_REPO }}/releases/latest > releases.json
-          echo "Curl done."
+          cat releases.json
           LATEST_TAG_NAME=$(jq .tag_name releases.json)
           echo "Comparing $LATEST_TAG_NAME with \"${{ env.RELEASE_TAG }}\""
           if [[ $LATEST_TAG_NAME == \"${{ env.RELEASE_TAG }}\" ]]
@@ -340,6 +351,7 @@ jobs:
               -H "Authorization: Bearer ${{ secrets.ENTANDO_BOT_TOKEN }}"\
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/${{ env.ENTANDO_RELEASES_REPO }}/releases?per_page=10 > releases.json
+            cat releases.json
             COUNT=$(jq length releases.json)
             for ((i=0;i<COUNT;i++)); do
               RELEASE_TAG_NAME=$(jq .[$i].tag_name releases.json)
