ENG-5164 WIP: Debugging crane issue

diff --git a/.github/workflows/entando-release.yml b/.github/workflows/entando-release.yml
--- a/.github/workflows/entando-release.yml
+++ b/.github/workflows/entando-release.yml
@@ -109,29 +109,31 @@ jobs:
           CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
         run: |
           for IMAGE in $(echo "$CLIENT_PAYLOAD" | jq -c '.images[]'); do
-            IMAGE_NAME=$(echo $IMAGE | jq -r '.name')
-            REPO_NAMESPACE=$(echo $DOCKER_HUB_REPO | jq -r '.docker_hub_namespace')
-            NEW_VERSION=$(echo $IMAGE | jq -r '.version')
-            echo $IMAGE_NAME
-            echo $REPO_NAMESPACE
-            echo $NEW_VERSION
-            NEW_DIGEST="$(crane digest ${REPO_NAMESPACE}:${NEW_VERSION})"
-            #if [[ $NEW_DIGEST = false ]]
-            #then
-            #  echo "::error :: Version '$NEW_VERSION' does not exist for '$IMAGE_NAME'"
-            #  exit 5
-            #fi
-            echo "This is the digest: ${NEW_DIGEST}"
-            ORIGINAL_VERSION=$(yq ".operator.relatedImages.$IMAGE_NAME.version" values.yaml)
-            ORIGINAL_SHA=$(yq ".operator.relatedImages.$IMAGE_NAME.sha256" values.yaml)
-            yq -i ".operator.relatedImages.$IMAGE_NAME.version = $NEW_VERSION" values.yaml
-            yq -i ".operator.relatedImages.$IMAGE_NAME.sha256 = $NEW_DIGEST" values.yaml
-            # Print the original and updated version and SHA digest of the Docker image
-            echo "Updating values.yaml"
-            echo "Image name: $IMAGE_NAME"
-            echo 'Original data: version="'$ORIGINAL_VERSION'", sha="'$ORIGINAL_SHA'"'
-            echo 'New data: version="'$NEW_VERSION'", sha='$NEW_DIGEST
-            echo ""
+            for DOCKER_HUB_REPO in $(echo "$DOCKER_HUB_REPOS" | jq -c '.images[]'); do
+              IMAGE_NAME=$(echo $IMAGE | jq -r '.name')
+              REPO_NAMESPACE=$(echo $DOCKER_HUB_REPO | jq -r '.docker_hub_namespace')
+              NEW_VERSION=$(echo $IMAGE | jq -r '.version')
+              echo $IMAGE_NAME
+              echo $REPO_NAMESPACE
+              echo $NEW_VERSION
+              NEW_DIGEST="$(crane digest ${REPO_NAMESPACE}:${NEW_VERSION})"
+              #if [[ $NEW_DIGEST = false ]]
+              #then
+              #  echo "::error :: Version '$NEW_VERSION' does not exist for '$IMAGE_NAME'"
+              #  exit 5
+              #fi
+              echo "This is the digest: ${NEW_DIGEST}"
+              ORIGINAL_VERSION=$(yq ".operator.relatedImages.$IMAGE_NAME.version" values.yaml)
+              ORIGINAL_SHA=$(yq ".operator.relatedImages.$IMAGE_NAME.sha256" values.yaml)
+              yq -i ".operator.relatedImages.$IMAGE_NAME.version = $NEW_VERSION" values.yaml
+              yq -i ".operator.relatedImages.$IMAGE_NAME.sha256 = $NEW_DIGEST" values.yaml
+              # Print the original and updated version and SHA digest of the Docker image
+              echo "Updating values.yaml"
+              echo "Image name: $IMAGE_NAME"
+              echo 'Original data: version="'$ORIGINAL_VERSION'", sha="'$ORIGINAL_SHA'"'
+              echo 'New data: version="'$NEW_VERSION'", sha='$NEW_DIGEST
+              echo ""
+            done
           done
 
       # Generating kustomization files for K8S and OCP environments
