ENG-5164 Updating values.yaml digest to be the generic one

diff --git a/.github/workflows/entando-release.yml b/.github/workflows/entando-release.yml
--- a/.github/workflows/entando-release.yml
+++ b/.github/workflows/entando-release.yml
@@ -98,6 +98,10 @@ jobs:
               exit 4
           fi
 
+      # Installing crane
+      - name: Installing crane
+        uses: imjasonh/setup-crane@v0.1
+
       # Update images versions and SHA digests in the values.yaml file
       - name: Set images versions and sha
         env:
@@ -106,60 +110,25 @@ jobs:
         run: |
           for IMAGE in $(echo "$CLIENT_PAYLOAD" | jq -c '.images[]'); do
             IMAGE_NAME=$(echo $IMAGE | jq -r '.name')
+            REPO_NAMESPACE=$(echo $DOCKER_HUB_REPO | jq -r '.docker_hub_namespace')
             NEW_VERSION=$(echo $IMAGE | jq -r '.version')
-            FOUND_IMAGE=false
-            FOUND_VERSION=false
-            for DOCKER_HUB_REPO in $(echo "$DOCKER_HUB_REPOS" | jq -c '.images[]'); do
-              REPO_NAME=$(echo $DOCKER_HUB_REPO | jq -r '.name')
-              REPO_NAMESPACE=$(echo $DOCKER_HUB_REPO | jq -r '.docker_hub_namespace')
-              REPO=$(echo $DOCKER_HUB_REPO | jq -r '.docker_hub_repository')
-              if [[ $IMAGE_NAME == $REPO_NAME ]]
-              then
-                FOUND_IMAGE=true
-                BASE_URL="https://hub.docker.com/v2/namespaces/$REPO_NAMESPACE/repositories/$REPO/tags?name="$NEW_VERSION"&page_size=1000"
-                echo "Querying docker hub: $BASE_URL"
-                curl -X GET $BASE_URL > result.json
-                COUNT=$(jq .count result.json)
-                # Check if the Docker image version exists on Docker Hub
-                if [[ $COUNT > 0 ]]
-                then
-                  for ((i=0;i<COUNT;i++)); do
-                    DOCKER_HUB_VERSION=$(jq .results[$i].name result.json)
-                    if [[ '"'$NEW_VERSION'"' == $DOCKER_HUB_VERSION ]]
-                    then
-                       FOUND_VERSION=true
-                       ORIGINAL_VERSION=$(yq ".operator.relatedImages.$IMAGE_NAME.version" values.yaml)
-                       ORIGINAL_SHA=$(yq ".operator.relatedImages.$IMAGE_NAME.sha256" values.yaml)
-                       SHA=$(jq .results[$i].images[0].digest result.json)
-                       SHA=${SHA//sha256:/}
-                       # Update the version and SHA digest of the Docker image in the values.yaml file
-                       yq -i ".operator.relatedImages.$IMAGE_NAME.version = $DOCKER_HUB_VERSION" values.yaml
-                       yq -i ".operator.relatedImages.$IMAGE_NAME.sha256 = $SHA" values.yaml
-                       # Print the original and updated version and SHA digest of the Docker image
-                       echo "Updating values.yaml"
-                       echo "Image name: $IMAGE_NAME"
-                       echo 'Original data: version="'$ORIGINAL_VERSION'", sha="'$ORIGINAL_SHA'"'
-                       echo 'New data: version="'$NEW_VERSION'", sha='$SHA
-                       echo ""
-                       break
-                    fi
-                  done
-                fi
-                rm result.json
-                # If the Docker image version doesn't exist on Docker Hub, exit with an error
-                if [[ $FOUND_VERSION = false ]]
-                then
-                  echo "::error :: Version '$NEW_VERSION' does not exist for '$IMAGE_NAME'"
-                  exit 5
-                fi
-              fi
-            done
-            # If the Docker image doesn't exist in the Docker Hub repositories configuration, exit with an error
-            if [[ $FOUND_IMAGE = false ]]
-            then
-              echo "::error :: Image '$IMAGE_NAME' does not exist in '$DOCKER_HUB_REPOS_CONFIG_URL'"
-              exit 6
-            fi
+            NEW_DIGEST="$(crane digest ${REPO_NAMESPACE}:${NEW_VERSION})"
+            #if [[ $NEW_DIGEST = false ]]
+            #then
+            #  echo "::error :: Version '$NEW_VERSION' does not exist for '$IMAGE_NAME'"
+            #  exit 5
+            #fi
+            echo "This is the digest: ${NEW_DIGEST}"
+            ORIGINAL_VERSION=$(yq ".operator.relatedImages.$IMAGE_NAME.version" values.yaml)
+            ORIGINAL_SHA=$(yq ".operator.relatedImages.$IMAGE_NAME.sha256" values.yaml)
+            yq -i ".operator.relatedImages.$IMAGE_NAME.version = $NEW_VERSION" values.yaml
+            yq -i ".operator.relatedImages.$IMAGE_NAME.sha256 = $NEW_DIGEST" values.yaml
+            # Print the original and updated version and SHA digest of the Docker image
+            echo "Updating values.yaml"
+            echo "Image name: $IMAGE_NAME"
+            echo 'Original data: version="'$ORIGINAL_VERSION'", sha="'$ORIGINAL_SHA'"'
+            echo 'New data: version="'$NEW_VERSION'", sha='$NEW_DIGEST
+            echo ""
           done
 
       # Generating kustomization files for K8S and OCP environments
